security:
  oauth2:
    resource:
      userInfoUri: http://192.168.3.195:8080/auth/realms/master/protocol/openid-connect/userinfo
      
management:
  security:
    enabled: false      
    
logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        data: debug
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.195:8761/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://192.168.3.195?useSSL=false
    username: root
    password: VIASOFT
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
  redis:
    host: 192.168.3.195
    port: 6379       

keycloak:
  ribbon:
    listOfServers: http://192.168.3.195:8080
  admin:
    username: admin
    password: admin
    
elastic:
  cluster:
    name: docker-cluster
  host: 192.168.3.195
  port: 9300
      