server:
  ip: 192.168.3.195
  
security:
  oauth2:
    resource:
      userInfoUri: http://${server.ip}:8080/auth/realms/master/protocol/openid-connect/userinfo
    client:
      accessTokenUri: http://${server.ip}:8080/auth/realms/master/protocol/openid-connect/token
      userAuthorizationUri: http://${server.ip}:8080/auth/realms/master/protocol/openid-connect/authorize
      clientId: viasoft

management:
  security:
    enabled: false      

logging:
  level:
    org:
      springframework:
        security: debug
        web: debug
        data: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.ip}:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://${server.ip}?useSSL=false
    username: root
    password: VIASOFT
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
  redis:
    host: ${server.ip}
    port: 6379
  rabbitmq:
    host: ${server.ip}
  cloud:
    bus:
      enabled: true
    stream:
      kafka:
        binder:
          zkNodes: ${server.ip}
          defaultZkPort: 2181
          brokers: ${server.ip}
          defaultBrokerPort: 9092

keycloak:
  admin:
    username: admin
    password: admin
    
elastic:
  cluster:
    name: docker-cluster
  host: ${server.ip}
  port: 9300
      