server:
  port: 8089

jms:
  brokerUrl: tcp://192.168.3.51:61616
  username:
  password:

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        type: trace
        generate_statistics: true

logging:
  level:
    org:
      hibernate:
        SQL: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

flyway:
  schemas: VIASELL